version: "3.8"

services:
  opa:
    image: openpolicyagent/opa:latest-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "policies"
    volumes:
      - ./policies:/workspace/policies:ro
    working_dir: /workspace
